// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgUh2BGEDLtjG4mz-VWSCq_ZF5ykSxvaM',
    appId: '1:189991414826:web:04aa8b6af149aafccda753',
    messagingSenderId: '189991414826',
    projectId: 'graduation-project-aad7b',
    authDomain: 'graduation-project-aad7b.firebaseapp.com',
    databaseURL: 'https://graduation-project-aad7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduation-project-aad7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjs2AjJI0_juAZhG6JGZwrp1QHlF3MynA',
    appId: '1:189991414826:android:94e1313ceac47246cda753',
    messagingSenderId: '189991414826',
    projectId: 'graduation-project-aad7b',
    databaseURL: 'https://graduation-project-aad7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduation-project-aad7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvAmxY7m4kRi1z98kggW6rGN4GleMjkEM',
    appId: '1:189991414826:ios:61e3f36f093b7386cda753',
    messagingSenderId: '189991414826',
    projectId: 'graduation-project-aad7b',
    databaseURL: 'https://graduation-project-aad7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduation-project-aad7b.appspot.com',
    iosBundleId: 'com.licensehome.licensehome',
  );
}
